name: tarim_proje
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  
  flutter_colorpicker: ^1.0.3

  # ðŸ”¥ Firebase paketleri
  firebase_auth_web: ^5.8.13
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_drawing_board: ^0.9.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  cached_network_image: ^3.4.1
  js: ^0.7.2
  url_launcher: ^6.3.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http: ^1.3.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - app.env
